config/routes.rb
Rails.application.routes.draw do
  
  resources :tweets, only:[:index,:new,:create,:edit,:update,:destroy] do
    collection do
      post :confirm
    end
  end
  
  
  
  root 'top#index'
  
  
  

end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
    
    validates:content,length:{maximum:140},presence:true
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/top_controller.rb
class TopController < ApplicationController
    
    def index
    end
    
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
    before_action :set_tweet,only:[:edit,:update,:destroy]
    
    def index
        @tweets = Tweet.all
    end
    
    def new
       if params[:back]
       @tweets = Tweet.new(tweets_params)
       else
       @tweets = Tweet.new
       end
    end
    
    def create
       @tweets = Tweet.new(tweets_params)
       if @tweets.save
          redirect_to tweets_path
       else
       render 'new' 
       end
    end
    
    def destroy
        @tweets = Tweet.find(params[:id])
        @tweets.destroy
        redirect_to tweets_path
    end
    
    def update
        @tweets = Tweet.find(params[:id])
        if @tweets.update(tweets_params)
            redirect_to tweets_path
        else
            rendr   'edit'
        end
    end
    
    def confirm
      @tweets = Tweet.new(tweets_params)
      render :new if @tweets.invalid?
    end
    
    private
     def tweets_params
        params.require(:tweet).permit(:content)
     end
     
    def set_tweet
     @tweets = Tweet.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
    
    def choose_new_or_edit
     if action_name =='new' || action_name == 'confirm'
        confirm_tweets_path
     elsif action_name == 'edit'
          tweet_path 
     end
    end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<div class="b">
<head>
  <title>Tweets</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width,initial-scale=1" >
</head>
<body>

<header>
  <ul>
  <li><%= link_to "ホーム",root_path %></li>
  <li><%= link_to "つぶやき",new_tweet_path %></li>
  <li><%= link_to "つぶやき一覧",tweets_path %></li>
  <li><img class="tweet" src="<%=asset_path "twitter.jpg"%>" width="20%"></li>
</ul>
</header>

<%= yield %>


<footer>
  <p>© 2017 Copyright Keita Morita</p>
</footer>
</div>
</body>
</html>

app/views/top/index.html.erb
        <p class="moji">No Run,No Life</p>
        <img class="gazo" src="<%= asset_path "run2.jpg" %>" width="28%">
        <h3>EXAM1の課題で作成した、Twitter同様の機能を備えたWebアプリです。</h3>
    
    

app/views/tweets/_form.html.erb
<%= form_for(@tweets,url:choose_new_or_edit) do |f| %>
<% if @tweets.errors.any? %>
<div class="error_explanation">
   <div><h2><%=@tweets.errors.count %>件のエラーがあります。</h2></div>

<ul>
    <% @tweets.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
</ul>
</div>
<% end %>

<%= f.label :いまどうしてる？,class:'what' %>
<%= f.text_area :content,class:'form-control'%>
<%= f.submit 'つぶやく',class:'btn btn-primary btn-block' %>

<% end %>

app/views/tweets/confirm.html.erb
<div class = "container">
    <div class = "col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
        <div class="tsubuyaki">以下の内容でつぶやく</div>
    <%= form_for(@tweets) do |f| %>
    <%= f.hidden_field :content %>
    
    <div class="naiyo">投稿内容:<%= @tweets.content %></div>
    <%= f.submit"登録",class:'btn btn-primary btn-block' %>
    <% end %>
    
    <%= form_for(@tweets,url: new_tweet_path,method:'get') do |f| %>
    <%= f.hidden_field :content %>
    <%= f.submit"戻る",name:'back',class:'btn btn-primary btn-block' %>
    <% end %>
</div>
</div>
    

app/views/tweets/edit.html.erb
<div class = "container">
    <div class = 'col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1'>
        <div class="hensyu">つぶやきを編集する</div>
        <%= render 'form' %>
    </div>
</div>
        

app/views/tweets/index.html.erb
<div class = "container">
    <div class = "wrapper col-md-8 col-md-offset-2 col-sm-10">
        <p><%=notice %></p>
        <div class="ichiran">つぶやき一覧</div>
        <% @tweets.each do |tweets| %>
        <div class = "row">
            <div class="contents"><%=tweets.content %></div>
            <%= link_to "編集",edit_tweet_path(tweets.id),class:'btn btn-default btn-sm btn-success' %>
            <%= link_to "削除",tweet_path(tweets.id),method: :delete,data:{confirm:'本当に削除しますか？'},class:'btn btn-default btn-sm btn-danger' %>
        </div>
        <% end %>
    </div>
</div>

app/views/tweets/new.html.erb
<div class="container">
 <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
     <%= render 'form' %>
</div>
</div>